// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>cloudmusic2upnp.DeviceController.UPnP.AvtEvent</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace cloudmusic2upnp.DeviceController.UPnP.AvtEvent
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("Event", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = false)]
    public partial class rootType
    {

        private InstanceIDtype[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("InstanceID", Order = 0)]
        public InstanceIDtype[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class InstanceIDtype
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private uint valField;

        [System.Xml.Serialization.XmlElementAttribute("AVTransportURI", typeof(AVTransportURItype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("AbsoluteCounterPosition", typeof(restrictedUnsignedIntVal), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("AbsoluteTimePosition", typeof(durationtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentMediaCategory", typeof(CurrentMediaCategorytype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentMediaDuration", typeof(durationtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentPlayMode", typeof(CurrentPlayModetype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentRecordQualityMode", typeof(CurrentRecordQualityModetype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentTrack", typeof(CurrentTracktype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentTrackDuration", typeof(durationtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentTrackMetadata", typeof(CurrentTrackMetadatatype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentTrackURI", typeof(CurrentTrackURItype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrentTransportActions", typeof(CurrentTransportActionstype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("DRMState", typeof(DRMStatetype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("NextAVTransportURI", typeof(NextAVTransportURItype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("NumberOfTracks", typeof(NumberOfTrackstype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PlaybackStorageMedium", typeof(storageMediumtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PossiblePlaybackStorageMedia", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PossibleRecordQualityMode", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PossibleRecordStorageMedia", typeof(string), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RecordMediumWriteStatus", typeof(RecordMediumWriteStatustype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RecordStorageMedium", typeof(storageMediumtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RelativeCounterPosition", typeof(intVal), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RelativeTimePosition", typeof(durationtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TransportPlaySpeed", typeof(TransportPlaySpeedtype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TransportState", typeof(TransportStatetype), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TransportStatus", typeof(TransportStatustype), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AVTransportURI.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("AVTransportURI.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class AVTransportURItype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DRMState.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("DRMState.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class DRMStatetype
    {

        private DRMStatetypeVal valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public DRMStatetypeVal val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    public enum DRMStatetypeVal
    {

        /// <remarks/>
        OK,

        /// <remarks/>
        UNKNOWN,

        /// <remarks/>
        PROCESSING_CONTENT_KEY,

        /// <remarks/>
        CONTENT_KEY_FAILURE,

        /// <remarks/>
        ATTEMPTING_AUTHENTICATION,

        /// <remarks/>
        FAILED_AUTHENTICATION,

        /// <remarks/>
        NOT_AUTHENTICATED,

        /// <remarks/>
        DEVICE_REVOCATION,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class restrictedUnsignedIntVal
    {

        private uint valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class intVal
    {

        private int valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentTransportActions.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentTransportActions.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentTransportActionstype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "NextAVTransportURI.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("NextAVTransportURI.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class NextAVTransportURItype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentTrackURI.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentTrackURI.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentTrackURItype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "anyURI")]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentTrackMetadata.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentTrackMetadata.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentTrackMetadatatype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "duration.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("duration.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class durationtype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentTrack.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentTrack.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentTracktype
    {

        private uint valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "NumberOfTracks.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("NumberOfTracks.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class NumberOfTrackstype
    {

        private uint valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentRecordQualityMode.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentRecordQualityMode.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentRecordQualityModetype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "RecordMediumWriteStatus.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("RecordMediumWriteStatus.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class RecordMediumWriteStatustype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "TransportPlaySpeed.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("TransportPlaySpeed.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class TransportPlaySpeedtype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentPlayMode.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentPlayMode.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentPlayModetype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "storageMedium.type", Namespace = "urn:schemas-upnp-org:av:av")]
    public partial class storageMediumtype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "CurrentMediaCategory.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("CurrentMediaCategory.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class CurrentMediaCategorytype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "TransportStatus.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("TransportStatus.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class TransportStatustype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "TransportState.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("TransportState.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class TransportStatetype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        AVTransportURI,

        /// <remarks/>
        AbsoluteCounterPosition,

        /// <remarks/>
        AbsoluteTimePosition,

        /// <remarks/>
        CurrentMediaCategory,

        /// <remarks/>
        CurrentMediaDuration,

        /// <remarks/>
        CurrentPlayMode,

        /// <remarks/>
        CurrentRecordQualityMode,

        /// <remarks/>
        CurrentTrack,

        /// <remarks/>
        CurrentTrackDuration,

        /// <remarks/>
        CurrentTrackMetadata,

        /// <remarks/>
        CurrentTrackURI,

        /// <remarks/>
        CurrentTransportActions,

        /// <remarks/>
        DRMState,

        /// <remarks/>
        NextAVTransportURI,

        /// <remarks/>
        NumberOfTracks,

        /// <remarks/>
        PlaybackStorageMedium,

        /// <remarks/>
        PossiblePlaybackStorageMedia,

        /// <remarks/>
        PossibleRecordQualityMode,

        /// <remarks/>
        PossibleRecordStorageMedia,

        /// <remarks/>
        RecordMediumWriteStatus,

        /// <remarks/>
        RecordStorageMedium,

        /// <remarks/>
        RelativeCounterPosition,

        /// <remarks/>
        RelativeTimePosition,

        /// <remarks/>
        TransportPlaySpeed,

        /// <remarks/>
        TransportState,

        /// <remarks/>
        TransportStatus,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "AVTransportURIMetaData.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("AVTransportURIMetaData.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class AVTransportURIMetaDatatype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "NextAVTransportURIMetaData.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("NextAVTransportURIMetaData.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class NextAVTransportURIMetaDatatype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "name.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/")]
    [System.Xml.Serialization.XmlRootAttribute("name.type", Namespace = "urn:schemas-upnp-org:metadata-1-0/AVT/", IsNullable = true)]
    public partial class nametype
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
}
