// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>cloudmusic2upnp</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>True</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;


namespace cloudmusic2upnp.DeviceController.UPnP.RcsEvent
{
    
    
    [System.Runtime.Serialization.DataContractAttribute(Name="rootType", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class rootType {
        
        private List<InstanceIDtype> itemsField;
        
        public rootType() {
            this.itemsField = new List<InstanceIDtype>();
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<InstanceIDtype> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="InstanceIDtype", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class InstanceIDtype {
        
        private List<object> itemsField;
        
        private List<ItemsChoiceType> itemsElementNameField;
        
        private uint valField;
        
        public InstanceIDtype() {
            this.itemsElementNameField = new List<ItemsChoiceType>();
            this.itemsField = new List<object>();
        }
        
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<object> Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Runtime.Serialization.DataMemberAttribute()]
        public List<ItemsChoiceType> ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valstring", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valstring {
        
        private string valField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valvolumeDBplusChannel", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valvolumeDBplusChannel {
        
        private short valField;
        
        private string channelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valunsignedShortPlusChannel", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valunsignedShortPlusChannel {
        
        private ushort valField;
        
        private string channelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valbooleanPlusChannel", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valbooleanPlusChannel {
        
        private bool valField;
        
        private string channelField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valshort", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valshort {
        
        private short valField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valunsignedShort", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valunsignedShort {
        
        private ushort valField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    [System.Runtime.Serialization.DataContractAttribute(Name="valpreset", Namespace="urn:schemas-upnp-org:metadata-1-0/RCS/")]
    public partial class valpreset {
        
        private string valField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string val {
            get {
                return this.valField;
            }
            set {
                this.valField = value;
            }
        }
    }
    
    public enum ItemsChoiceType {
        
        /// <remarks/>
        AllowedTransformSettings,
        
        /// <remarks/>
        BlueVideoBlackLevel,
        
        /// <remarks/>
        BlueVideoGain,
        
        /// <remarks/>
        Brightness,
        
        /// <remarks/>
        ColorTemperature,
        
        /// <remarks/>
        Contrast,
        
        /// <remarks/>
        GreenVideoBlackLevel,
        
        /// <remarks/>
        GreenVideoGain,
        
        /// <remarks/>
        HorizontalKeystone,
        
        /// <remarks/>
        Loudness,
        
        /// <remarks/>
        Mute,
        
        /// <remarks/>
        PresetNameList,
        
        /// <remarks/>
        RedVideoBlackLevel,
        
        /// <remarks/>
        RedVideoGain,
        
        /// <remarks/>
        Sharpness,
        
        /// <remarks/>
        TransformSettings,
        
        /// <remarks/>
        VerticalKeystone,
        
        /// <remarks/>
        Volume,
        
        /// <remarks/>
        VolumeDB,
    }
}
