// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>cloudmusic2upnp.DeviceController.UPnP.RcsEvent</NameSpace><Collection>Array</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace cloudmusic2upnp.DeviceController.UPnP.RcsEvent
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("Event", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = false)]
    public partial class rootType
    {

        private InstanceIDtype[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("InstanceID", Order = 0)]
        public InstanceIDtype[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class InstanceIDtype
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private uint valField;

        [System.Xml.Serialization.XmlElementAttribute("AllowedTransformSettings", typeof(valstring), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("BlueVideoBlackLevel", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("BlueVideoGain", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Brightness", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("ColorTemperature", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Contrast", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("GreenVideoBlackLevel", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("GreenVideoGain", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("HorizontalKeystone", typeof(valshort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Loudness", typeof(valbooleanPlusChannel), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Mute", typeof(valbooleanPlusChannel), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("PresetNameList", typeof(valpreset), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RedVideoBlackLevel", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("RedVideoGain", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Sharpness", typeof(valunsignedShort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("TransformSettings", typeof(valstring), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("VerticalKeystone", typeof(valshort), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Volume", typeof(valunsignedShortPlusChannel), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("VolumeDB", typeof(valvolumeDBplusChannel), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public uint val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.string", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.string", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valstring
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.volumeDBplusChannel", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.volumeDBplusChannel", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valvolumeDBplusChannel
    {

        private short valField;

        private string channelField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.unsignedShortPlusChannel", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.unsignedShortPlusChannel", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valunsignedShortPlusChannel
    {

        private ushort valField;

        private string channelField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.booleanPlusChannel", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.booleanPlusChannel", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valbooleanPlusChannel
    {

        private bool valField;

        private string channelField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.short", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.short", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valshort
    {

        private short valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public short val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.unsignedShort", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.unsignedShort", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valunsignedShort
    {

        private ushort valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "val.preset", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/")]
    [System.Xml.Serialization.XmlRootAttribute("val.preset", Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IsNullable = true)]
    public partial class valpreset
    {

        private string valField;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:schemas-upnp-org:metadata-1-0/RCS/", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        AllowedTransformSettings,

        /// <remarks/>
        BlueVideoBlackLevel,

        /// <remarks/>
        BlueVideoGain,

        /// <remarks/>
        Brightness,

        /// <remarks/>
        ColorTemperature,

        /// <remarks/>
        Contrast,

        /// <remarks/>
        GreenVideoBlackLevel,

        /// <remarks/>
        GreenVideoGain,

        /// <remarks/>
        HorizontalKeystone,

        /// <remarks/>
        Loudness,

        /// <remarks/>
        Mute,

        /// <remarks/>
        PresetNameList,

        /// <remarks/>
        RedVideoBlackLevel,

        /// <remarks/>
        RedVideoGain,

        /// <remarks/>
        Sharpness,

        /// <remarks/>
        TransformSettings,

        /// <remarks/>
        VerticalKeystone,

        /// <remarks/>
        Volume,

        /// <remarks/>
        VolumeDB,
    }
}
